version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose FastAPI on port 8000
    volumes:
      - ./backend:/app # Mount the backend directory
    environment:
      - PYTHONUNBUFFERED=1 # Optional: to see logs in real-time

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501" # Expose Streamlit on port 8501
    volumes:
      - ./frontend:/app # Mount the frontend directory
    environment:
      - PYTHONUNBUFFERED=1 # Optional: to see logs in real-time
